export const SET_USER_DATA = {
  API_SET_USER_DATA: 'API_SET_USER_DATA',
  API_SET_USER_SUCCESS: 'API_SET_USER_SUCCESS',
  API_SET_USER_ERROR: 'API_SET_USER_ERROR',

  // Logout..
  USER_LOGOUT: 'USER_LOGOUT',
};
